language: ruby
rvm:
- 2.3.3

script: bundle install
script: bundle exec jekyll build

# branch whitelist, only for GitHub Pages
branches:
  only:
  - master

sudo: false # route your build to the container-based infrastructure for a faster build